### ISSUE TITLE
Cannot get the same results in each run

### ISSUE THREAD

**Issue by PKUZHOU** [CMU-SAFARI/Pythia#1]
Thank you for providing the useful framework. 
I am doing some follow-up research based on your code. However, an annoying thing is that when I run the same simulation command twice, I will get slightly different IPC numbers. This can be observed in each line of IPC log. 

I guess there may be some issues about the random seed usage, however I have not found any clues (I have checked that the champsim_seeds are the same in two runs). Do you have any suggestions?

Thank you!

**Comment by PKUZHOU** [comment]
I got it.  It is due to the srand() function in the LLC replacement module:  https://github.com/CMU-SAFARI/Pythia/blob/778e2fcfc8b44506db86f44ec46d9be86c1faa17/replacement/drrip.llc_repl#L27

**Comment by rahulbera** [comment]
Hi @PKUZHOU, I have pushed the necessary changes to the DRRIP and SHiP replacement policy initialization. This should fix the run-to-run variations. Please let me know if you have found any other source of randomness in the code. We can reopen this issue again.

**Comment by PKUZHOU** [comment]
Thank you for your reply!
Yes, after changing the two lines Ican get the same results now.
