### ISSUE TITLE
Hello. Does the prefetch address generated by Pythia sequentially access L1D, L2, LLC, and DRAM? I mean, does the prefetch address generated by Pythia access the cache and main memory in a traditional manner?

### ISSUE THREAD

**Issue by szuhzw** [CMU-SAFARI/Pythia#14]
Hello. Does the prefetch address generated by Pythia sequentially access L1D, L2, LLC, and DRAM? I mean, does the prefetch address generated by Pythia access the cache and main memory in a traditional manner? @rahulbera

**Comment by rahulbera** [comment]
Yes.
