### ISSUE TITLE
Query: The Mega Links for Parsec and Ligra are not working 

### ISSUE THREAD

**Issue by shubbham1219** [CMU-SAFARI/Pythia#3]
@rahulbera The Mega Links for Parsec and Ligra are not working. Kindly update

**Comment by rahulbera** [comment]
Hi @shubbham1219, thanks for letting us know. I’m checking how to resolve this issue.

**Comment by rahulbera** [comment]
Hi @shubbham1219, the problem was stemming from broken megatools download link. 67d43da49e057e73391ff6878683dc6987fb5745 should fix the issue. 

Closing this issue for now.
