### ISSUE TITLE
Can't locate Trace.pm in @INC

### ISSUE THREAD

**Issue by faradawn** [CMU-SAFARI/Pythia#6]
Hi,

When running `create_jobfile.pl`, I encountered a module not found error:
```
cc@pythsia-1:~/Pythia/experiments$ perl ../scripts/create_jobfile.pl --exe $PYTHIA_HOME/bin/perceptron-multi-multi-no-ship-1core --tlist MICRO21_1C.tlist --exp MICRO21_1C.exp --local 1 > jobfile.sh
Can't locate Trace.pm in @INC (you may need to install the Trace module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at ../scripts/create_jobfile.pl line 5.
BEGIN failed--compilation aborted at ../scripts/create_jobfile.pl line 5.
```
I tried looking it up online but still didn't know how how to install the Trace module. Is `Trace.pm` a file somewhere in the repo, or should I install it in some way?

Thanks in advance!

**Comment by rahulbera** [comment]
Hi @faradawn, Trace.pm is a custom-written Perl module present inside `scripts/` directory. Have you sourced the `setvars.sh` file as mentioned in the README? It should setup PYTHIA_HOME appropriately, which is used to find the Trace module path. 

If you have indeed sourced `setvars.sh` then check Perl version. Pythia is tested with Perl 3.20 and I have experienced this error before while using a newer version of Perl (I believe you're using 5.34). Downgrading the Perl version should help in this case.

**Comment by faradawn** [comment]
Hi @rahulbera,

Sourcing `setvars.sh` allowed `create_jobfile.pl` to produce a jobfile without error! My perl version was still v5.34.0.

But when executing `source ../jobfile.sh`, the terminal stuck. I can try it a few more times.

Thanks very much, and can close the issue!
